### ISSUE TITLE
工具外链失效，无法下载！

### ISSUE THREAD

**Issue by acusp** [ctf-wiki/ctf-tools#5]
如题，希望可以跟新链接。谢谢🙏

**Comment by iromise** [comment]
请明确说一下哪一个工具链接失效了。

**Comment by acusp** [comment]
所有需要使用 http://down.40huo.cn/ 域名的外链都失效了。显示如下内容：

> You do not have permission to get URL 'xxx' from this server.

**Comment by 40huo** [comment]
哦，我知道了，CDN 的防盗链没加上 GitHub 的白名单，已经加了，等他刷新吧。
